# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: study-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - study-network

  # DB 관리 도구
  adminer:
    image: adminer:4.8.1
    container_name: study-app-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - study-network
    depends_on:
      - postgres
  
volumes:
  postgres_data:
    driver: local
  
networks:
  study-network:
    driver: bridge
